# Generated by Django 2.2.20 on 2021-11-21 12:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isiolo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Isiolo_Towns',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('area', models.FloatField()),
                ('perimeter', models.FloatField()),
                ('town_name', models.CharField(max_length=254)),
                ('town_id', models.FloatField()),
                ('town_type', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': ' Isiolo Towns',
            },
        ),
    ]
