# Generated by Django 2.2.20 on 2022-01-06 10:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isiolo', '0002_isiolo_towns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('e', models.FloatField()),
                ('n', models.FloatField()),
                ('order_field', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Control Stations',
            },
        ),
        migrations.AlterModelOptions(
            name='isiolo_towns',
            options={'verbose_name_plural': 'Isiolo Towns'},
        ),
    ]
