# Generated by Django 2.2.20 on 2022-01-06 15:36

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('isiolo', '0003_auto_20220106_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportIncidence',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=50, verbose_name='')),
                ('status', models.CharField(choices=[('Destroyed', 'Destroyed'), ('Missing', 'Missing'), ('Existing', 'Existing'), ('Re-Established', 'Re-Established'), ('Undefined', 'Undefined')], max_length=20)),
                ('username', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=40)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Report Incidences',
            },
        ),
        migrations.AddField(
            model_name='controls',
            name='status',
            field=models.CharField(choices=[('Destroyed', 'Destroyed'), ('Missing', 'Missing'), ('Existing', 'Existing'), ('Re-Established', 'Re-Established'), ('Undefined', 'Undefined')], default='Existing', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StaffProfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telnumber', models.CharField(max_length=10, verbose_name='Phone Number')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('photo', models.ImageField(upload_to='', verbose_name='Profile Picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
