# Generated by Django 2.2.20 on 2022-01-24 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isiolo', '0005_auto_20220111_1624'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Controls',
        ),
    ]
