# Generated by Django 2.2.20 on 2022-01-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isiolo', '0006_delete_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportincidence',
            name='station_name',
            field=models.CharField(max_length=50, verbose_name='Station name'),
        ),
    ]
